### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yoshida0835** [yoshida0835/furima-39605#21]
自身のフリマアプリのURL | 本番環境(RenderまたはHeroku)のURL
https://furima-39605.onrender.com/

Basic認証のIDとパスワード | 
ID:admin
パスワード:2222

出品者用のメールアドレスとパスワード | 本番環境で使用可能なユーザーの情報
メールアドレス：yoshida@gmail.com
パスワード：yoshida0911

購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
メールアドレス：megu@gmail.com
パスワード：megu0802

**Comment by shodai-ito** [comment]
@yoshida0835 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`ユーザー管理機能`**
- [ ] **エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
赤文字のエラーと黒文字のエラーが表示され、内容が重複しております。
エラー内容が重複しないよう、修正をお願いいたします。
<img width="754" alt="スクリーンショット 2023-11-15 16 19 41" src="https://github.com/yoshida0835/furima-39605/assets/62537107/19200cf2-5a20-47a9-91f8-1517811fe31e">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yoshida0835** [comment]
修正完了いたしました。
ご確認の程宜しくお願い致します。

**Comment by moom1122** [comment]
@yoshida0835 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by yoshida0835** [comment]
ありがとうございました！
